
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jorge
 */
public class CongruencialMult extends javax.swing.JFrame {

    /**
     * Creates new form CongruencialMult
     */
    public CongruencialMult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadio = new javax.swing.ButtonGroup();
        cmbP = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btngenerar = new javax.swing.JButton();
        txtsemilla = new javax.swing.JTextField();
        cmbD = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSerie = new javax.swing.JLabel();
        rbDec = new javax.swing.JRadioButton();
        rbBin = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "11", "13", "19", "21", "27", "29", "37", "53", "59", "61", "67", "69", "77", "83", "91" }));

        jLabel1.setText("Semilla no deber ser divisible para 2 o 5 y relativament primo a (M)");

        jLabel2.setText("El multiplicador se representa en la formula (a=200t±p)");

        txtT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTActionPerformed(evt);
            }
        });

        jLabel3.setText("Modulo (M): 10 a la potencia (d)");

        btngenerar.setText("Generar Serie");
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });

        cmbD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabel4.setText("m:10   y   d:");

        jLabel5.setText("Semilla");

        jLabel6.setText("t:");

        jLabel7.setText("p:");

        lblSerie.setText("Serie");

        grupoRadio.add(rbDec);
        rbDec.setSelected(true);
        rbDec.setText("Decimal");
        rbDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDecActionPerformed(evt);
            }
        });

        grupoRadio.add(rbBin);
        rbBin.setText("Binario");
        rbBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtsemilla, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btngenerar))
                            .addComponent(lblSerie)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(rbDec)
                        .addGap(57, 57, 57)
                        .addComponent(rbBin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDec)
                    .addComponent(rbBin))
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsemilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cmbP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btngenerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSerie)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTActionPerformed

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        if (rbDec.isSelected()) {
            Double s=Double.parseDouble(txtsemilla.getText().toString());
            Double t=Double.parseDouble(txtT.getText().toString());
            String valP = (String) cmbP.getSelectedItem().toString();
            Double p = Double.parseDouble(valP);
            String valD = (String) cmbD.getSelectedItem().toString();
            int d = Integer.parseInt(valD);
            Double a=200*t+p;
            Double m;
            int[] v = new int[2];
            int[] e = new int[2];
            int i=1;
            int j=0;
            int k=0;
            int comp=2;
            m=Math.pow(10, d);
            if (s % 2 == 0 || s % 5 == 0||rPrimo(s,m)) {
                JOptionPane.showMessageDialog(null, "El valor semilla no cumple los requisitos ingrese otro");
            }else{
                if (d < 5) {
                    int valor=2;
                    Double x=m;
                    while(x>1){
                        if(x%valor==0){
                            if(valor>comp){
                                comp=valor;
                                k++;
                            }
                            e[k]=valor;
                            v[k]=i;
                            x=x/valor;
                            i++; 
                        }else{
                            j++;
                            i=1;
                            valor=valor+1;
                        } 
                    }
                    Double p1=Math.pow(e[0], v[0]-1)*(e[0]-1);
                    Double p2=Math.pow(e[1], v[1]-1)*(e[1]-1);
                    Double mcm=Math.min(p1,p2);
                    int num1=(int)p1.doubleValue();
                    int num2=(int)p2.doubleValue();
                    System.out.printf(mcm.toString()); 
                    double numero;  
                    String texto= "<html><body>n        Xn";
                    for (int o=1; o<=mcm(num1,  num2); o++){
                        numero = (a*s) % m;   
                        System.out.println( o +"  "+numero); 
                        texto+= "<br>"+o +"       "+numero;
                        s = numero;  
                    }
                    texto+="</body></html>";
                    lblSerie.setText(texto);
                }else{
                    m=0.00;
                    d = d - 2;
                    m =5 * (Math.pow(10, d));
                    double numero;
                    String texto= "<html><body>n        Xn";
                    for (int o=1; o<=m; o++){
                        numero = (a*s) % m;   
                        System.out.println( o +"  "+numero); 
                        texto+= "<br>"+o +"       "+numero;
                        s = numero;  
                    }
                    texto+="</body></html>";
                    lblSerie.setText(texto);
                }
                } 
        } else {
            Double s=Double.parseDouble(txtsemilla.getText().toString());
            Double t=Double.parseDouble(txtT.getText().toString());
            String valD = (String) cmbD.getSelectedItem().toString();
            int d = Integer.parseInt(valD);
            Double m=Math.pow(2, d-2);
            if (s % 2 == 0 ||rPrimo(s,m)) {
                JOptionPane.showMessageDialog(null, "El valor semilla no cumple los requisitos ingrese otro");
            }else{
                Double a=8*t-3;
                double numero=0;
                String texto= "<html><body>n        Xn";
                Double comp=(a*s) % m; 
                numero = (a*s) % m; 
                s = numero; 
                int i=1;
                do{
                    System.out.println( i+"  "+numero); 
                    texto+= "<br>"+i +"       "+numero;
                    numero = (a*s) % m;   
                    s = numero; 
                    i++;
                }while(comp!=numero);
                texto+="</body></html>";
                lblSerie.setText(texto);
            }  
        }  
          
    }//GEN-LAST:event_btngenerarActionPerformed

    private void rbBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBinActionPerformed
        jLabel1.setText("Semilla puede ser cual entero impar relativamente primo a (M)");
        jLabel2.setText("El multiplicador se representa en la formula (a=8t±3)");
        cmbP.setEnabled(false);
        jLabel7.setText("-");
        jLabel3.setText("Modulo (M): 2 a la potencia (d) formula:2^d-2");
        jLabel4.setText("m:2   y   d:");
        
        
    }//GEN-LAST:event_rbBinActionPerformed

    private void rbDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDecActionPerformed
        jLabel1.setText("Semilla no deber ser divisible para 2 o 5 y relativament primo a (M)");
        jLabel2.setText("El multiplicador se representa en la formula (a=200t±p)");
        cmbP.setEnabled(true);
        jLabel7.setText("p:");
        jLabel3.setText("Modulo (M): 10 a la potencia (d)");
        jLabel4.setText("m:10   y   d:");
        
        
    }//GEN-LAST:event_rbDecActionPerformed
    public boolean rPrimo(Double s, Double m) {
        Double may=m;
        if (s >= m) {
            may = s;
        } 
        int cont = 0;
        for (int i = 2; i <= may; i++) {
            if (s % i == 0 && m % i == 0) {
                cont++;
            }
        }
        return cont!=0;
    }
    public int mcm(int num1, int num2) {
        int mcm = 0;
        int a = Math.max(num1, num2);
        int b = Math.min(num1, num2);
        mcm = (a/mcd(a, b))*b;
        return mcm;
    }
     public static int mcd(int num1, int num2) {
        int mcd = 0;
        int a = Math.max(num1, num2);
        int b = Math.min(num1, num2);
        do {
            mcd = b;
            b = a%b;
            a = mcd;
        } while(b!=0);
        return mcd;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CongruencialMult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CongruencialMult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CongruencialMult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CongruencialMult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CongruencialMult().setVisible(true);
                
            }
        });
    }
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngenerar;
    private javax.swing.JComboBox cmbD;
    private javax.swing.JComboBox cmbP;
    private javax.swing.ButtonGroup grupoRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JRadioButton rbBin;
    private javax.swing.JRadioButton rbDec;
    private javax.swing.JTextField txtT;
    private javax.swing.JTextField txtsemilla;
    // End of variables declaration//GEN-END:variables
}
